import { AdminAnimal, User } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Juan Pérez',
    email: 'juan@example.com',
    role: 'rancher',
    animalsCount: 45,
    lastActive: '2 horas',
    status: 'active',
    location: {
      address: 'Av. Paucarpata Km 8.5',
      city: 'Arequipa',
      state: 'Arequipa',
      country: 'Perú',
      latitude: -16.409,
      longitude: -71.5375,
      farmName: 'Estancia Misti',
    },
  },
  {
    id: '2',
    name: 'María González',
    email: 'maria@example.com',
    role: 'rancher',
    animalsCount: 32,
    lastActive: '1 día',
    status: 'active',
    location: {
      address: 'Carretera Central Km 12',
      city: 'Huancayo',
      state: 'Junín',
      country: 'Perú',
      latitude: -12.0653,
      longitude: -75.2049,
      farmName: 'Fundo Los Andes',
    },
  },
  {
    id: '3',
    name: 'Carlos López',
    email: 'carlos@example.com',
    role: 'rancher',
    animalsCount: 28,
    lastActive: '3 días',
    status: 'inactive',
    location: {
      address: 'Distrito Characato s/n',
      city: 'Arequipa',
      state: 'Arequipa',
      country: 'Perú',
      latitude: -16.4735,
      longitude: -71.4934,
      farmName: 'Hacienda Valle Verde',
    },
  },
  {
    id: '4',
    name: 'Ana Rodríguez',
    email: 'ana.rodriguez@email.com',
    role: 'rancher',
    animalsCount: 67,
    lastActive: '5 horas',
    status: 'active',
    location: {
      address: 'Km 15 Carretera Huancayo-Concepción',
      city: 'Huancayo',
      state: 'Junín',
      country: 'Perú',
      latitude: -12.1234,
      longitude: -75.1890,
      farmName: 'Ganadería San José',
    },
  },
  {
    id: '5',
    name: 'Roberto Mendoza',
    email: 'roberto.mendoza@gmail.com',
    role: 'rancher',
    animalsCount: 89,
    lastActive: '30 minutos',
    status: 'active',
    location: {
      address: 'Sector Sabandia Km 7',
      city: 'Arequipa',
      state: 'Arequipa',
      country: 'Perú',
      latitude: -16.4567,
      longitude: -71.5123,
      farmName: 'Estancia El Volcán',
    },
  },
  {
    id: '6',
    name: 'Patricia Flores',
    email: 'patricia.flores@outlook.com',
    role: 'rancher',
    animalsCount: 23,
    lastActive: '2 días',
    status: 'active',
    location: {
      address: 'Valle del Mantaro s/n',
      city: 'Jauja',
      state: 'Junín',
      country: 'Perú',
      latitude: -11.7756,
      longitude: -75.4973,
      farmName: 'Finca La Pradera',
    },
  },
  {
    id: '7',
    name: 'Miguel Torres',
    email: 'miguel.torres@yahoo.com',
    role: 'rancher',
    animalsCount: 156,
    lastActive: '12 horas',
    status: 'active',
    location: {
      address: 'Pampa Cangallo Km 22',
      city: 'Arequipa',
      state: 'Arequipa',
      country: 'Perú',
      latitude: -16.3890,
      longitude: -71.4567,
      farmName: 'Hacienda Tres Volcanes',
    },
  },
  {
    id: '8',
    name: 'Carmen Vásquez',
    email: 'carmen.vasquez@hotmail.com',
    role: 'rancher',
    animalsCount: 41,
    lastActive: '1 semana',
    status: 'inactive',
    location: {
      address: 'Carretera Huancayo-Chupaca Km 8',
      city: 'Huancayo',
      state: 'Junín',
      country: 'Perú',
      latitude: -12.0987,
      longitude: -75.2345,
      farmName: 'Granja Santa Rosa',
    },
  },
];

export const mockAdminAnimals: AdminAnimal[] = [
  {
    id: 'A001',
    name: 'Bella',
    breed: 'Angus',
    owner: 'Juan Pérez',
    rfidTag: 'E200001234567890',
    status: 'healthy',
    registeredDate: '2024-10-01',
  },
  {
    id: 'A002',
    name: 'Max',
    breed: 'Holstein',
    owner: 'María González',
    rfidTag: 'E200001234567891',
    status: 'treatment',
    registeredDate: '2024-09-28',
  },
  {
    id: 'A003',
    name: 'Duke',
    breed: 'Brahman',
    owner: 'Carlos López',
    rfidTag: 'E200001234567892',
    status: 'healthy',
    registeredDate: '2024-09-25',
  },
  {
    id: 'A004',
    name: 'Luna',
    breed: 'Jersey',
    owner: 'Ana Rodríguez',
    rfidTag: 'E200001234567893',
    status: 'healthy',
    registeredDate: '2024-09-22',
  },
  {
    id: 'A005',
    name: 'Toro',
    breed: 'Charolais',
    owner: 'Roberto Mendoza',
    rfidTag: 'E200001234567894',
    status: 'quarantine',
    registeredDate: '2024-09-20',
  },
  {
    id: 'A006',
    name: 'Estrella',
    breed: 'Simmental',
    owner: 'Patricia Flores',
    rfidTag: 'E200001234567895',
    status: 'healthy',
    registeredDate: '2024-09-18',
  },
  {
    id: 'A007',
    name: 'Capitán',
    breed: 'Hereford',
    owner: 'Miguel Torres',
    rfidTag: 'E200001234567896',
    status: 'treatment',
    registeredDate: '2024-09-15',
  },
  {
    id: 'A008',
    name: 'Paloma',
    breed: 'Holstein',
    owner: 'Carmen Vásquez',
    rfidTag: 'E200001234567897',
    status: 'healthy',
    registeredDate: '2024-09-12',
  },
  {
    id: 'A009',
    name: 'Rayo',
    breed: 'Brahman',
    owner: 'Juan Pérez',
    rfidTag: 'E200001234567898',
    status: 'healthy',
    registeredDate: '2024-09-10',
  },
  {
    id: 'A010',
    name: 'Canela',
    breed: 'Brown Swiss',
    owner: 'María González',
    rfidTag: 'E200001234567899',
    status: 'pregnant',
    registeredDate: '2024-09-08',
  },
  {
    id: 'A011',
    name: 'Diamante',
    breed: 'Limousin',
    owner: 'Carlos López',
    rfidTag: 'E200001234567800',
    status: 'healthy',
    registeredDate: '2024-09-05',
  },
  {
    id: 'A012',
    name: 'Reina',
    breed: 'Angus',
    owner: 'Ana Rodríguez',
    rfidTag: 'E200001234567801',
    status: 'treatment',
    registeredDate: '2024-09-03',
  },
  {
    id: 'A013',
    name: 'Sultán',
    breed: 'Nelore',
    owner: 'Roberto Mendoza',
    rfidTag: 'E200001234567802',
    status: 'healthy',
    registeredDate: '2024-09-01',
  },
  {
    id: 'A014',
    name: 'Princesa',
    breed: 'Jersey',
    owner: 'Patricia Flores',
    rfidTag: 'E200001234567803',
    status: 'lactating',
    registeredDate: '2024-08-28',
  },
  {
    id: 'A015',
    name: 'Emperador',
    breed: 'Gelbvieh',
    owner: 'Miguel Torres',
    rfidTag: 'E200001234567804',
    status: 'healthy',
    registeredDate: '2024-08-25',
  },
];